type QueryKey = {
  SNIPPETS: "SNIPPETS";
  STACKS: "STACKS";
  LANGUAGES: "LANGUAGES";
};

export const QUERY_KEYS: QueryKey = {
  SNIPPETS: "SNIPPETS",
  STACKS: "STACKS",
  LANGUAGES: "LANGUAGES",
};
